include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Recommended rules
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    avoid_print: false # Allow prints for debugging in development
    
    # Code organization
    sort_constructors_first: true
    sort_pub_dependencies: true
    directives_ordering: true
    
    # Performance
    avoid_slow_async_io: true
    close_sinks: true
    
    # Error prevention
    avoid_types_as_parameter_names: true
    no_duplicate_case_values: true
    valid_regexps: true
    
    # Style
    camel_case_types: true
    library_names: true
    file_names: true
    package_names: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true