targets:
  $default:
    builders:
      retrofit_generator:
        options:
          generate_for:
            - lib/core/network/api_client.dart
      json_serializable:
        options:
          explicit_to_json: true
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          ignore_unannotated: false
          include_if_null: true
      hive_generator:
        enabled: true