name: umkm_mahasiswa_platform
description: Platform Digitalisasi UMKM & Mahasiswa Indonesia
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  get_it: ^7.6.4  # Add this line
  flutter:
    sdk: flutter
  
  # Core UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  dio: ^5.3.4
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Storage & Database
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Firebase - COMMENTED TEMPORARILY until configuration is added
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # firebase_messaging: ^14.7.10
  # firebase_analytics: ^10.7.4
  
  # Image & Media
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2
  
  # UI Components
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  
dev_dependencies:
  test: ^1.24.6   # Add this
  mockito: ^5.4.2 # Add this
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1
  
flutter:
  uses-material-design: true
  
  # Assets commented temporarily - add folders/files later
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  
  # Fonts commented temporarily - add font files later
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700